#
#  _     _                   _______ _                 _          
# (_)   | |                 (_______) |               | |  v1.6.9
#  _____| |_____ _____ ____  _      | |__  _   _ ____ | |  _  ___ 
# |  _   _) ___ | ___ |  _ \| |     |  _ \| | | |  _ \| |_/ )/___)
# | |  \ \| ____| ____| |_| | |_____| | | | |_| | | | |  _ (|___ |
# |_|   \_)_____)_____)  __/ \______)_| |_|____/|_| |_|_| \_|___/ 
#                     |_|                                         
#
# Copyright © 2015-2022 Geitenijs, all rights reserved.
# Information & Support: https://www.spigotmc.org/resources/23307
#
# general:
#   colourfulconsole: Console messages will be coloured when this is enabled.
#   debug: When set to true, the plugin will log more information to the console.
#   releaseallprotection: Do you want to restrict the 'release all' command to the console?
# updates:
#   check: When enabled, the plugin will check for updates. No automatic downloads, just a subtle notification in the console.
#   notify: Would you like to get an in-game reminder of a new update? Requires permission 'keepchunks.notify.update'.

#
#  _     _                   _______ _                 _          
# (_)   | |                 (_______) |               | |  v1.6.8
#  _____| |_____ _____ ____  _      | |__  _   _ ____ | |  _  ___ 
# |  _   _) ___ | ___ |  _ \| |     |  _ \| | | |  _ \| |_/ )/___)
# | |  \ \| ____| ____| |_| | |_____| | | | |_| | | | |  _ (|___ |
# |_|   \_)_____)_____)  __/ \______)_| |_|____/|_| |_|_| \_|___/ 
#                     |_|                                         
#
# Copyright © 2015-2021 Geitenijs, all rights reserved.
# Information & Support: https://www.spigotmc.org/resources/23307
#
# general:
#   colourfulconsole: Console messages will be coloured when this is enabled.
#   debug: When set to true, the plugin will log more information to the console.
#   releaseallprotection: Do you want to restrict the 'release all' command to the console?
# updates:
#   check: When enabled, the plugin will check for updates. No automatic downloads, just a subtle notification in the console.
#   notify: Would you like to get an in-game reminder of a new update? Requires permission 'keepchunks.notify.update'.
general:
  colourfulconsole: true
  debug: false
  releaseallprotection: true
updates:
  check: true
  notify: true
