# ########### Chat Engine ############
# Custom Chat Engine, handles titles,
# formatting, json support and more.
# Also handles join & quit messages
#
# Dev: J.Hunter
# ###############################

on chat:
	cancel event
	
	# Emoji Renderer

	if message contains "<3":
		replace "<3" in message with "❤"
	if message contains ":smoke:":
		replace ":smoke:" in message with " ̳ ̳ ̳ ̳ ͙ ڪ "
	if message contains ":)":
		replace ":)" in message with "☺"
	if message contains "wut":
		replace "wut" in message with "ಠ_ಠ"
	if message contains ":pick:":
		replace ":pick:" in message with "⛏"
	if message contains ":fire:":
		replace "fire" in message with "🔥"
	if message contains ":hug:":
		replace ":hug:" in message with "(づ｡◕‿‿◕｡)づ"
	if message contains ":fu:":
		replace ":fu:" in message with "凸(-_-)凸"
	if message contains ":tableflip:":
		replace ":tableflip:" in message with "(╯°□°）╯︵ ┻━┻"
	
	if sender has permission "sys.rank.owner":
		send formatted "<tooltip:&7[&fClick me to pm <##ff1100>%player's display name%&7]><suggest command:/msg %player% >%{prefix.%player%}% <##ff1100>%player's display name%<reset>&f: %message%" to all players
		send formatted "<##ff1100>%player's display name%<reset>&f: %message%" to console
	else if sender has permission "sys.rank.leader":
		send formatted "<tooltip:&7[&fClick me to pm <##9b59b6>%player's display name%&7]><suggest command:/msg %player% >{prefix.%player%}<##9b59b6>%player's display name%<reset>&f: %message%" to all players
		send formatted "<##9b59b6>%player's display name%<reset>&f: %message%" to console
	else if sender has permission "sys.rank.member":
		send formatted "<tooltip:&7[&fClick me to pm <##881A51>%player's display name%&7]><suggest command:/msg %player% >{prefix.%player%} <##881A51>%player's display name%<reset>&f: %message%" to all players		
		send formatted "<##881A51>%player's display name%<reset>&f: %message%" to console
	else:
		broadcast "<##ff0000>&l⚠ &r<##9b59b6>BROKEN RANK <##ff0000>&l⚠ &7%sender% ❱ %message%"
	#
#
on first join:
	broadcast "%{botprefix}% %player% has joined for the first time!"
#
	
on join:
	broadcast "&7[&a+&7] &7%player% has joined the server"
	set {prefix.%player%} to ""
#
on quit:
	broadcast "&7[&c-&7] &7%player% has left the server"
#


# Emoji list command
command /emoji:
	trigger:
		send "&e----------------------Emoji List----------------------"
		send "':)' -> ☺"
		send "'<3' -> ❤"
		send "'wut' -> ಠ_ಠ"
		send "':pick:' -> ⛏"
		send "':fire:' -> 🔥"
		send "':hug:' -> (づ｡◕‿‿◕｡)づ"
		send "':fu:' -> 凸(-_-)凸"
		send "':tableflip' -> (╯°□°）╯︵ ┻━┻"
		send "&e----------------------------------------------------"